/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colombo.institute.of.studies;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class HRAssistantLogin extends javax.swing.JFrame {

    private static final String Username="root";
    private static final String Password="";
    private static final String Dataconn="jdbc:mysql://localhost:3306/colombodb";
  
    Connection sqlconn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    
     public String emailPattern="^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$";
   public String mobileNumberPattern="^[0-9]*$";
   
    public HRAssistantLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        HARLemail = new javax.swing.JTextField();
        HRALpassword = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel4.setText("Login");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setText("Login");

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Menu");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("forget password?");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 180, 60));

        HARLemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HARLemailActionPerformed(evt);
            }
        });
        getContentPane().add(HARLemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 290, 40));

        HRALpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRALpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(HRALpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 260, 290, 40));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Menu");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 110, 40));

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Login");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 340, -1, -1));

        sh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                shMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                shMouseReleased(evt);
            }
        });
        getContentPane().add(sh, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 230, 20, 20));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 80, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel2.setText("LOGIN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 40, 170, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/exit.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 10, 40, 40));

        jLabel3.setBackground(new java.awt.Color(51, 255, 0));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 380, 610));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images/Blue and White Simple Start-up Business Animated Presentation (1).gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 620));

        setSize(new java.awt.Dimension(1033, 621));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        int a= JOptionPane.showConfirmDialog(null,"Do you really want to Close Application ","Select",JOptionPane.YES_NO_OPTION);
       if(a==0)
       {
           System.exit(0);
       }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void HARLemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HARLemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HARLemailActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
     
         if(HARLemail.getText().isEmpty()||HRALpassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Fill up the form properly","Error",JOptionPane.ERROR_MESSAGE );
            
        }else 
        
         
        try{
            Class.forName("com.mysql.jdbc.Driver");
            sqlconn=DriverManager.getConnection(Dataconn, Username, Password);
            pst=sqlconn.prepareStatement("SELECT Email,Password FROM hrassistant WHERE Email=?");
            String us=String.valueOf(HARLemail.getText());
            
            pst.setString(1, us);
            rs=pst.executeQuery();
              
               
            if (rs.next()==false){
                JOptionPane.showMessageDialog(this, "Email Not Found");
                
            }else{
                String pass=String.valueOf(HRALpassword.getText());
                if(pass.equals(rs.getString("Password"))){
                     
                     JOptionPane.showMessageDialog(this, "Login Successfull");
                     addnewemployeee ADEP = new addnewemployeee();
                     ADEP.setVisible(true);
                     this.hide();
                }
                else{
                     JOptionPane.showMessageDialog(this, "Incorrect Password");
                }
            }
            
            
            
        }catch(Exception ex){
          JOptionPane.showMessageDialog(this, ex);
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        Menu Menu = new Menu();
        Menu.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        newfogetpasswordhas nfhs = new newfogetpasswordhas();
        nfhs.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void HRALpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRALpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRALpasswordActionPerformed

    private void shMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shMousePressed
        ImageIcon icon=new ImageIcon("icon/view.png");//create object and load image to it from image path
        Image img=icon.getImage();//convert icon image to image for the resize
        Image imgscale=img.getScaledInstance(20, 20, Image.SCALE_SMOOTH);//resize the image with your parameters
        ImageIcon scaleicon= new ImageIcon(imgscale);//create icon object with scale image
        sh.setIcon(scaleicon);//set icon to the label
        HRALpassword.setEchoChar((char)0);

    }//GEN-LAST:event_shMousePressed

    private void shMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_shMouseReleased
        ImageIcon icon=new ImageIcon("icon/hidden.png");//create object and load image to it from image path
        Image img=icon.getImage();//convert icon image to image for the resize
        Image imgscale=img.getScaledInstance(20, 20, Image.SCALE_SMOOTH);//resize the image with your parameters
        ImageIcon scaleicon= new ImageIcon(imgscale);//create icon object with scale image
        sh.setIcon(scaleicon);//set icon to the label
        HRALpassword.setEchoChar('*');
    }//GEN-LAST:event_shMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HRAssistantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HRAssistantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HRAssistantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HRAssistantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HRAssistantLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HARLemail;
    private javax.swing.JPasswordField HRALpassword;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel sh;
    // End of variables declaration//GEN-END:variables
}
